title: Multiple Regex Extractor
description: >-
  This will return a CSV file of all strings the given regex matches in
  the selected files for all of the patterns passed as parameters.
instructions: ''
type: object
documents:
  - selected
properties:
  regex:
    type: array
    default: [""]
    items:
      title: Regex
      type: string
      format: regex
required: [regex]
